apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisperx-helm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # Adjust according to the size of your models
