apiVersion: v1
kind: Service
metadata:
  name: {{ include "whisperx-helm.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9080
    protocol: TCP
  selector:
    {{- include "whisperx-helm.selectorLabels" . | nindent 4 }}
